//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KLTN.Common.Resources.UserResource", typeof(UserResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string CreateAt {
            get {
                return ResourceManager.GetString("CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo bởi.
        /// </summary>
        public static string CreateBy {
            get {
                return ResourceManager.GetString("CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tham gia : .
        /// </summary>
        public static string DateJoin {
            get {
                return ResourceManager.GetString("DateJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when edit user in service.
        /// </summary>
        public static string EditServiceLogError {
            get {
                return ResourceManager.GetString("EditServiceLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thất bại.
        /// </summary>
        public static string FailEditUser {
            get {
                return ResourceManager.GetString("FailEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quỹ.
        /// </summary>
        public static string Fund {
            get {
                return ResourceManager.GetString("Fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử tạo đấu giá.
        /// </summary>
        public static string HistoryCreateAuction {
            get {
                return ResourceManager.GetString("HistoryCreateAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử tham gia đấu giá.
        /// </summary>
        public static string HistoryJoinAuction {
            get {
                return ResourceManager.GetString("HistoryJoinAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string HomeAdmin {
            get {
                return ResourceManager.GetString("HomeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chi tiết.
        /// </summary>
        public static string Infor {
            get {
                return ResourceManager.GetString("Infor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người dùng: .
        /// </summary>
        public static string InforUserColon {
            get {
                return ResourceManager.GetString("InforUserColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên: .
        /// </summary>
        public static string NameColon {
            get {
                return ResourceManager.GetString("NameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm cá nhân.
        /// </summary>
        public static string ProductPersonal {
            get {
                return ResourceManager.GetString("ProductPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhập.
        /// </summary>
        public static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lần đấu giá.
        /// </summary>
        public static string TimesAuction {
            get {
                return ResourceManager.GetString("TimesAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lần đấu giá thành công.
        /// </summary>
        public static string TimesAuctionSuccess {
            get {
                return ResourceManager.GetString("TimesAuctionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lần tạo đấu giá.
        /// </summary>
        public static string TimesCreateAuction {
            get {
                return ResourceManager.GetString("TimesCreateAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lần thành công.
        /// </summary>
        public static string TimesSuccess {
            get {
                return ResourceManager.GetString("TimesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết người dùng.
        /// </summary>
        public static string TitleDetail {
            get {
                return ResourceManager.GetString("TitleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật người dùng.
        /// </summary>
        public static string TitleEdit {
            get {
                return ResourceManager.GetString("TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách người dùng.
        /// </summary>
        public static string TitleIndex {
            get {
                return ResourceManager.GetString("TitleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User | Create.
        /// </summary>
        public static string TitleUserCreate {
            get {
                return ResourceManager.GetString("TitleUserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User | Detail.
        /// </summary>
        public static string TitleUserDetail {
            get {
                return ResourceManager.GetString("TitleUserDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User | Edit.
        /// </summary>
        public static string TitleUserEdit {
            get {
                return ResourceManager.GetString("TitleUserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User | Index.
        /// </summary>
        public static string TitleUserIndex {
            get {
                return ResourceManager.GetString("TitleUserIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thể loại đã đấu giá.
        /// </summary>
        public static string TotalCategoryAuction {
            get {
                return ResourceManager.GetString("TotalCategoryAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string UrlCreate {
            get {
                return ResourceManager.GetString("UrlCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string UrlDetail {
            get {
                return ResourceManager.GetString("UrlDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string UrlEdit {
            get {
                return ResourceManager.GetString("UrlEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách.
        /// </summary>
        public static string UrlIndex {
            get {
                return ResourceManager.GetString("UrlIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quỹ người dùng : .
        /// </summary>
        public static string UserFund {
            get {
                return ResourceManager.GetString("UserFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý người dùng.
        /// </summary>
        public static string UserManager {
            get {
                return ResourceManager.GetString("UserManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền người dùng: .
        /// </summary>
        public static string UserRoleColon {
            get {
                return ResourceManager.GetString("UserRoleColon", resourceCulture);
            }
        }
    }
}
